# Generated by Django 5.2.1 on 2025-05-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('form_factor', models.CharField(max_length=50)),
                ('rgb', models.BooleanField()),
                ('included_fans', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('compatible_sockets', models.JSONField()),
                ('noise_level_db', models.FloatField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performance_tier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('clock_speed_ghz', models.FloatField()),
                ('cores', models.IntegerField()),
                ('cache_mb', models.IntegerField()),
                ('memory_types', models.JSONField()),
                ('integrated_gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=50)),
                ('performance_level', models.CharField(max_length=20)),
                ('socket_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('vram_gb', models.IntegerField()),
                ('core_clock_mhz', models.IntegerField()),
                ('boost_clock_mhz', models.IntegerField()),
                ('power_draw_w', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video_output_interface', models.JSONField()),
                ('purpose', models.CharField(max_length=50)),
                ('performance_tier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('size_inches', models.FloatField()),
                ('resolution', models.CharField(max_length=20)),
                ('refresh_rate_hz', models.IntegerField()),
                ('panel_type', models.CharField(max_length=20)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video_output_interface', models.JSONField()),
                ('purpose', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('socket_type', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
                ('supported_memory_types', models.JSONField()),
                ('max_memory_gb', models.IntegerField()),
                ('memory_slots', models.IntegerField()),
                ('pci_express_slots', models.IntegerField()),
                ('m2_slots', models.IntegerField()),
                ('sata_ports', models.IntegerField()),
                ('integrated_wifi', models.BooleanField()),
                ('integrated_audio', models.BooleanField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supported_cpu_tiers', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('wattage', models.IntegerField()),
                ('modular', models.CharField(max_length=50)),
                ('efficiency_rating', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=50)),
                ('performance_tier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('capacity_gb', models.IntegerField()),
                ('modules', models.IntegerField()),
                ('speed_mhz', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('ecc', models.BooleanField()),
                ('rgb', models.BooleanField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voltage', models.FloatField()),
                ('form_factor', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('performance_tier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('interface', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
                ('capacity_gb', models.IntegerField()),
                ('read_speed_mb_s', models.IntegerField()),
                ('write_speed_mb_s', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_m2_slot', models.BooleanField()),
                ('requires_sata_port', models.BooleanField()),
                ('purpose', models.CharField(max_length=50)),
                ('performance_tier', models.CharField(max_length=20)),
            ],
        ),
    ]
