# Generated by Django 5.2.1 on 2025-05-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitor',
        ),
    ]
